### PR TITLE
Added Apps and Solutions category with initial pages

### PR DESCRIPTION
**Pull request by jvelasc25**
migrated documentation for BMS solutions from Wiki

### CODE REVIEW

**Comment by gastmaier** [comment]
Hi Joyce!

I took a look on your PR, a made a review commit at 3107d79d4faba3f14708e35e5618fb9247474575
Since the current branch has a merge conflict, I first rebased onto main, being your commit rebased d71a2f4a786f953297a4bc37708c301aad710090 .

## Here is what I changed:

* Trailing white-space
* Use :download: role for download links, to ensure these files are copied over during the doc build.
* Use [:adi:](https://analogdevicesinc.github.io/doctools/docs_guidelines.html#adi-role) role for analog.com links
* Use [:dokuwiki:](https://analogdevicesinc.github.io/doctools/docs_guidelines.html#dokuwiki-role) for wiki.analog.com links
* For images with captions replace with `figure:: :caption: {Caption}`
* Added a  "bold-first-column", "bold-header" to [table styling](https://analogdevicesinc.github.io/doctools/docs_guidelines.html#tables), and use that for the ad-cellpackbm-sl specifications table.
* Changed the nesting of the EVB user guides to:
  - Overview: most content on the page
  - Guides&Samples Software: For other pages
  - Help and Support: Footer section.
 
Attached is ad-cellpackbm as a PDF  to give a better idea on the resulting table of contents:
[output-ad-cellpackbm-sl.pdf](https://github.com/user-attachments/files/18142564/output-ad-cellpackbm-sl.pdf)

[The PDF is generated with the following YAML](https://analogdevicesinc.github.io/doctools/cli.html#custom-doc)
```yaml
# Custom doc builder template
# ---------------------------
# Generated with adi_doctools 0.3.51

#project: "AD-BMSE2E3W-SL"
project: "AD-CELLPACKBM-SL"
description: "Quick Start Guide"

# Dirs and files to include
# First level is repository name
include:
  #- documentation/solutions/reference-designs/ad-bmse2e3w-sl
  - documentation/solutions/reference-designs/ad-cellpackbm-sl

# Create toctree for entry point page
# Pages without a explicit entry point will be searched and globed
# until the root of the source doc is reached, which may include
# undesired additional pages/sections.
entry-point:
  - caption:
    files:
      #- documentation/solutions/reference-designs/ad-bmse2e3w-sl/index.rst
      - documentation/solutions/reference-designs/ad-cellpackbm-sl/index.rst
```

**Comment by thorenscientific** [comment]
Hi Jorge,
I built this locally and it looks great. I suspect we'll end up rearranging things in time; the "Apps and Solutions" category may end up with a new name and / or home. As long as we're good with that, then merging this will help the conversation along.
Also, this might be a good home for some of the CftL user guides, a lot of the older ones are quite similar in structure, with a separate software user guide.

**Comment by gastmaier** [comment]
I'm taking the freedom to force push and merge with the review commit then.
Of course we can still move things around later.
One thing I noticed it that in the toctrees is much better to use `:glob:` since most of the merge conflicts are just adding more files to the toctree that could be simply `*/index` to auto add them.

**Comment by jvelasc25** [comment]
Hi Jorge and Mark,
Thank you for reviewing my PR and making the necessary adjustments. I'll take note of all changes, so I can apply them to my future documents/commits.

**Pull request merged**
